export const imageTypes = [
  "image/png",
  "image/jpeg",
  "image/jpg",
  "image/gif",
  "image/svg+xml",
  "image/webp",
  "image/bmp",
  "image/apng",
  "image/tiff",
  "image/ico",
];
export const videoTypes = [
  "video/mp4",
  "video/webm",
  "video/ogg",
  "video/quicktime",
  "video/x-msvideo",
  "video/x-ms-wmv",
  "video/mpeg",
  "video/3gpp",
  "video/3gpp2",
  "video/avi",
  "video/flv",
  "video/mov",
  "video/ts",
  "video/mkv",
];
