import type { Metadata } from "next";
import { Bricolage_Grotesque } from "next/font/google";
import "../../globals.css";
import { Toaster } from "react-hot-toast";

export const metadata: Metadata = {
  title: "Paymefans React Application",
  description: "Generated by create next app",
};

const font = Bricolage_Grotesque({
  weight: ["200", "300", "400", "500", "600", "700", "800"],
  subsets: ["latin"],
  display: "swap",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={font.className}>
        <Toaster
          position="top-center"
          toastOptions={{
            duration: 10000,
            style: {
              fontSize: "16px",
              borderRadius: "10px",
              fontFamily: "system-ui",
            },
          }}
        />
        {children}
      </body>
    </html>
  );
}
