import PostEditor from '@/components/route_component/post-editor';
import axiosInstance from '@/utils/axios';
import { Metadata } from 'next';
import { cookies } from 'next/headers';

export const metadata: Metadata = {
    title: "Create Post",
    description: "Generated by create next app",
}

interface EditPostProps {
    params: {
        id: string;
    }
}

const EditPost = async ({ params }: EditPostProps) => {
    const token = cookies().get('token')?.value
    const response = await axiosInstance.get(`/editpost/${params.id}`, {
        headers: {
            Authorization: `Bearer ${token}`
        }
    });
    const posts = response.data.data

    return (
        <div className="h-full">
            <PostEditor posts={posts} />
        </div >
    );
};

export default EditPost;
