import type { Metadata } from "next";
import { UploadProgressProvider } from "@/contexts/UploadProgressContext";
import PostEditor from "@/features/post/PostEditorOptimized";
import { PostProviderWrapper } from "@/providers/PostProviderWrapper";

export const metadata: Metadata = {
  title: "Create Post",
  description: "Generated by create next app",
};

const NewPost = () => {
  return (
    <div className="h-full">
      <UploadProgressProvider>
        <PostProviderWrapper>
          <PostEditor />
        </PostProviderWrapper>
      </UploadProgressProvider>
    </div>
  );
};

export default NewPost;
