import "../globals.css";
import type { Metadata } from "next";
// import { Inter } from "next/font/google";
import localFont from "next/font/local";
import MenuButtons from "@/components/modals/menu_buttons";
import SideModels from "@/components/models/side_models";
import Header from "@/components/common/header";
import SideBar from "@/components/common/sidebar";
import { Toaster } from "react-hot-toast";
import { Toaster as SonnerToast } from "sonner";
import QueryProvider from "@/providers/query-provider";
import getUserData from "@/utils/data/user-data";
import PostComponentPreview from "@/components/post/full-component-preview";
import { UserContextProvider } from "@/lib/userUseContext";
import { UserPointsContextProvider } from "@/contexts/user-points-context";
import Loader from "@/components/common/loader";
import ToggleWishListProvider from "@/contexts/toggle-wishlist";
import WishList from "@/components/sub_components/wishlist";
import { GeistSans } from "geist/font/sans";
import { MessagesConversationProvider } from "@/contexts/messages-conversation-context";
import UserAccountSupendedScreen from "@/components/sub_components/user-account-suspended-screen";

// const font = Inter({
//   weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
//   subsets: ["latin", "latin-ext"],
//   display: "swap",
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const revalidate = 300;
export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await getUserData();

  if (user && user.active_status === false) {
    return (
      <html>
        <body
          className={`bg-white dark:bg-gray-950 min-h-screen flex items-center justify-center ${GeistSans.className}`}
        >
          <UserAccountSupendedScreen user={user} />
        </body>
      </html>
    );
  }

  return (
    <html lang="en">
      <body
        className={`
          ${GeistSans.className}
                 dark:bg-gray-950 min-h-screen`}
      >
        <UserContextProvider user={user}>
          <QueryProvider>
            <MessagesConversationProvider>
              <UserPointsContextProvider>
                <Loader />
                <Toaster
                  toastOptions={{
                    duration: 5000,
                    style: {
                      fontSize: "14px",
                      fontWeight: "500",
                      border: "1px solid #CC0DF8",
                      borderRadius: "100vmax",
                    },
                  }}
                />
                <SonnerToast
                  richColors
                  position="top-center"
                  toastOptions={{
                    closeButton: true,
                    duration: 10000,
                    style: {
                      fontSize: "16px",
                      borderRadius: "100vmax",
                    },
                  }}
                />
                <div className="relative grid h-screen lg:grid-cols-8">
                  <MessagesConversationProvider>
                    <ToggleWishListProvider>
                      <div className="col-span-2">
                        <SideBar />
                      </div>
                      <div className="relative h-screen col-span-6 overflow-auto border-r border-pink-50">
                        <Header />
                        <div className="grid lg:grid-cols-6 pt-[73px] lg:pt-[48px] h-screen">
                          <div className="flex flex-col h-full col-span-3">
                            <div className="w-full h-full md:border-r border-primary-dark-pink/40 dark:border-slate-800">
                              {children}
                            </div>
                          </div>
                          <SideModels />
                        </div>
                      </div>
                      <WishList />
                    </ToggleWishListProvider>
                  </MessagesConversationProvider>
                  <MenuButtons />
                  {/* <ModalComponent /> */}
                </div>
                <PostComponentPreview />
              </UserPointsContextProvider>
            </MessagesConversationProvider>
          </QueryProvider>
        </UserContextProvider>
      </body>
    </html>
  );
}
